### ISSUE TITLE
Add filesystem notification system

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#16]
## New commands
- `dcumn` (debug continue until mount notification)
- `mn` (mount notifications, to start inotify against current pid, or any)
- `mn pid` (specify pid)
- `mn /etc` (specify path)
- `mn /etc 30482`  (specify path and pid)
## Resources
- [iOS/OSX filemon](http://newosxbook.com/src.jl?tree=listings&file=3-filemon.c)
- [Linux](http://man7.org/tlpi/code/online/diff/inotify/demo_inotify.c.html)

**Comment by trufae** [comment]
This can be done with r2frida and fsmon, no need to reimplement this in r2 imho because it will imply code injection, duplicating code, etc. i may end up making fsmon a library so other projects can use it. But for now i think it's safe to remove this from the wishlist

* https://github.com/nowsecure/fsmon
