### ISSUE TITLE
Display unmapped data differently

### ISSUE THREAD

**Issue by ret2libc** [radareorg/ideas#215]
When printing data (e.g. pxw, Visual Mode, etc.) unmapped regions are displayed with `0xff` (or alternatively with another value specified by `io.0xff`) but that seems to me very confusing because it's hard to understand when it's really 0xff or just unmapped region/end of file.

As an example, I was looking at a very short file:
<img width="523" alt="screen shot 2018-02-15 at 09 48 12" src="https://user-images.githubusercontent.com/562321/36247725-60ec89f2-1235-11e8-80d6-6990408bfdb2.png">
<img width="555" alt="screen shot 2018-02-15 at 09 51 14" src="https://user-images.githubusercontent.com/562321/36247861-cbf29782-1235-11e8-8797-db199f013a98.png">

From the screenshots it's hard to tell how many bytes are accessible in this file (there are 8 bytes there, being `\xca\xfe\xba\xbe\xff\xff\xff\xff`, though it looks like only 4 are there)

I suggest to:
1. Display unmapped data with `-`(or something else which is not a number)
2. Give a color/bold to `ffffffff` as all the others data (if you see in the ascii representation, the first 4 bytes are bold, but the ff are not, as the unmapped data)

**Comment by trufae** [comment]
e io.unalloc is there for some time already. We probably want to 

* kill coreblock
* enable this option by default
* add more tests and support it everywhere

Main issue for not enabling it is performance. We need an api in io to return a bitmask that can be applied to the read buffer instead of having to check for every byte if its mapped or not.

Closing this issue because what’s being descibred is implemented, and all the details and comments are already in plan to be done
