### ISSUE TITLE
maddr must be = baddr by default?

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#277]
This way, the memory space will be linear filling the gaps of the sections mapped in there.
It can verified by opening a mach0 file like this:
on OSX:

```
$ r2 -m 0x100000000 /bin/ls
```

This behaviour can be also emulated with a section:

```
r2 -c 'S 0 0x100000000 $s $s mapbase mr' -qc 'x@0x100000000' /bin/ls
```

maybe this is just a problem with mach0...

```
r2 -c 'S 0 $B $s $s map mr' -qc 'x@0x100000000'  /bin/ls
```

**Comment by ret2libc** [comment]
Not clear what this issue is about. Could you explain a bit more?

**Comment by trufae** [comment]
maddr is no longer a thing because in siol on pa-mode the bins are loaded at address 0

**Comment by trufae** [comment]
the idea behind this issue is that if you open a binary that is ASLRable, the base address may be set to the address where the bin is mapped. this way with va and pa modes you may be able to get the same addresspace view. Note that S doesnt exist anymore.

So i think we can close this pre-siol issue because even if it makes sense to me is no longer possible and the current approach is less confusing
