### ISSUE TITLE
use an unit test library more than only regression testing for code coverage

### ISSUE THREAD

**Issue by gogo2464** [radareorg/ideas#348]
## Description

I would love to use and share codecov code coverage.

I just suggest to choose a good c unit test library for testing and I will implement 1000 tests.

In order to avoid depedencies, let's use conditional compilation for unit tests

#ifdef TESTING
    #include <cunit.h>
#endif

I quiclky suggest  cunit

If really you want no dependencies we could get a look at the gcc option -ftest-coverage that might create coverage file from assert.  I must check the doc. THis way sounds perfect because we could hook the regression tests to an assertion and then get the coverage file.

Assign me to this issue please. I will create coverage file from assert and then upload then to codecov (even if the push will not be glorious lol. We have to face on the truth).

**Comment by trufae** [comment]
This existed in the past but it was removed from the ci because it was too slow, code coverage is useless if nobody contributes and also codecov.io was pwned and all the projects using it was affected. And yes it was using the testsuite to compute the coverage but the whole thing took like 2-3h to run and i dont think that benefits us much for such long ci times

**Comment by gogo2464** [comment]
in my humble opinion tests are really really important. Codecov seems better now.

I suggest to try to get coverage on already implemented regression test with the assert already coded. 

I am trying to. I will tell you if it is possible.

**Comment by trufae** [comment]
I agree with you tests are important but the codev job took about 3h to run. I dont want to wait that much even if im the only one comiting. feel free to submit a pr adding it if you care i have other priorities than having 100% coverage right now because i prefer to implement missing features and fix bugs on already eziting code

**Comment by gogo2464** [comment]
I suggest to do it on a different and optional ci flow. so that the people will be able to fastly check the first regression test, we can quickly merge and then we see later if the real tests fails.

THis is the easy part. Now I have to force people to use CUnit. When I see the difficulty to force them to use testing on regression tests... Sounds very hard. I will simpluy add documentation on the README.md and on the book. I will see if it is respected.

**Comment by radare** [comment]
i see several issues in your statements:

* there is no people. im the only one doing code here
* there's a unit test already, but it basically tests crappy and broken apis that should be changing
* testing commands allows me to get much better code coverage with much less effort
* i have 0 plans to force anybody to do anything, proof shows that just burns people and reduces contributions

but in an ideal world, with clean code, contributors, and fairies, contractors and other magical creatures we could be doing that yes

**Comment by gogo2464** [comment]
The first point is mostly a good new from another points of view, because if there are few contributors, we could control more the code.

The second point shows... we have to provide more documentation! Do not kill me please. I like to document. I will add more documentation. I swear you.

I have nothing against your third statement. We could use only regression test if we could provide coverage to codecov with this. I doubt of that.

The last point is particulary embarassing. If no contributors will be present there might be less PR...

At last but not least, I am particulary afraid about the future of radare2. rizin has exactly the same philosophy and wants to provide more testing so:

1. it will drain r2 contributors
2. either rizin dies in the future and everyone migrate to r2 easily thank to same commands or the worst might happend ...

Sorry for the last point. I love r2 I am just very very afraid!!!

**Comment by radare** [comment]
You are free to document whatever you want, i dont have the time to document wrong apis, i prefer to spend this time to rewrite them properly instead. I also agree that documentation is useful and handy, i just dont have the time or find it a priority for my as long as im the only developer.

I dont care much about rizin, I was deeply deceived, and that's in part why i expect nothing from anybody and i dont plan to ask anybody to do anything. I tried to achieve at least a minimum of cooperation to avoid repeating work between both projects because it was clear that this people didnt wanted me in the project. But that was clearly not in their plans, so I just keep doing for my own.

radare2 will not die, at least until I die.

Im also worried about the future of the project, but i'm also worried about the future of the planet and the humanity. But it's all lies down to the fact that it's all driven by humans that do nothing or do wrong things. But ive been developing radare2 alone 13 of the 18 years of its existance (the people behind the fork appeared after me doing this alone for 8 years), and i wont stop doing it because i love the project and ive been learning a lot in the process, as well as helping other people to learn and achieve things they couldnt before r2 existed.

Also i tend to think that forking (rizin is not the first fork of radare that happen) is a good thing as it shows its a good idea and there's a need for this thing. But as said, the marketshare is quite big, and there are many other reverse engineering tools.

Kids nowadays don't care about free software, and even less about cli tools. Most people prefer to click buttons and pirate commercial software before contributing.

Don't be afraid about the future. The best that can happen is that we all die and all that suffering goes away. So better chill and keep pushing yourself to learn and do things you enjoy instead of fighting a wall :)

**Comment by gogo2464** [comment]
The rizin people make a terrible mistake with the idea to deny you. You litterally added and removed a total of 5 000 000 lines of code of radare2 when I just did 5 000 !!!!


> radare2 will not die, at least until I die.
You are precisely right. And I think instead of fighting a wall, we just have to deturn it with finding an answer. Do you think that private compagnies could have an interest in contributing in radare2? They already have for Ghidra. They have for gdb (very different than r2 (not a reversing tool)). Let's talk in discord?

**Comment by gogo2464** [comment]
I got a look at the contributors of rizin. Most of them do pwn. And yes a lot of people in bug bounty are immature...

On a first look I thank if rizin is not the first fork it might mean that they could not survive years. I am deeply thinking because there seems to be a tiny community. Not big but more spread than r2.

I am definitely worring to death.

**Comment by gogo2464** [comment]
In the worst worst case, according to the command `git log --author="pancake"` I can see rizin is a 2021 fork. So you lost "only" 2 years of work...

But if you can not join them on your own fork... Yes the situation is very very bad.

**Comment by trufae** [comment]
There are good developers behind rizin and I wish them the best, it's just sad that it was no way to have a common base, but i guess that despite bug fixes their development roadmap doesnt fit with r2. I have backported some fixes from them, as well as they did from r2 in the past. But they are isolated projects, no common development. It's opensource at the end anyone is free to do this.

The situation could end up into much better, but also much worse. Rizin focus on shipping less features but refine them more, with less code to maintain and a gui. Radare2 in the other side, have a wider range of features and use cases supports more archs, portability, extensibility, forensics, dynamic instrumentation and focus on cli and experimental.

Anyway, this is not the place to talk about this and it's just past.
